#
# https://github.com/itzg/dockerfiles/tree/master/minecraft-server
# 

version: '3.7'

services:
  mc-server:
    image: ${IMAGE}
    container_name: mc-server
    restart: always
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "20k"
        max-file: "10"
    ports:
      - "25565:25565"
    environment:
      - EULA
      - TYPE
      - ALLOW_NETHER
      - ANNOUNCE_PLAYER_ACHIEVEMENTS
      - ENABLE_COMMAND_BLOCK
      - GENERATE_STRUCTURES
      - SPAWN_ANIMALS
      - SPAWN_MONSTERS
      - SPAWN_NPCS
      - WHITELIST
      - ENABLE_QUERY
      - OPS
      - MOTD
    volumes:
      - type: bind
        source: ${LOCAL_MC_DATA}
        target: /data
      # - type: volume
      #   source: mc-data
      #   target: /data

# volumes:
#   mc-data:
#     driver: local
