apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: MineCraft Server
  labels:
    app: MineCraft Server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-server
  template:
    metadata:
      labels:
        app: mc-server
    spec:
      containers:
        - image: eu.gcr.io/minecraft-server-185418/itzg
          name: mc-server
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: password
          ports:
            - containerPort: 25565
              name: mc-server
          volumeMounts:
            - name: mc-persistent-storage
              mountPath: /data
      volumes:
        - name: mc-persistent-storage
          gcePersistentDisk:
            pdName: mc-world-disk
            fsType: ext4